
services:
  fastapi_backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis_cache
    depends_on:
      - redis_cache

  streamlit_frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://fastapi_backend:8000
    depends_on:
      - fastapi_backend

  redis_cache:
    image: redis:alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v3.10.0-rc.1-distroless
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"